export const headerLinks = [
    {
      label: "Residential",
      link: "/residential",
      sublinks: [
        { label: "Houses", link: "/house-cleaning" },
        { label: "Move Out/Move In", link: "/residential-move-in-move-out" },
        { label: "Apartment", link: "/apartment-cleaning" },
        { label: "Baseboard", link: "/baseboard" },
        { label: "House Cleaning & Sanitizing", link: "/house-sanitation" },
      ],
    },
    {
      label: "Commercials",
      link: "/commercials",
      sublinks: [
        { label: "Industries", link: "industries" },
        { label: "Grocery stores", link: "/grocery-stores" },
        { label: "Bank and Financial", link: "/bank-financial" },
        { label: "Distribution Centers", link: "/distribution-centers" },
        { label: "Educational Facilities", link: "/educational-facilities" },
        { label: "Urgent Care Center", link: "/urgent-care" },
        { label: "Drugstores & Pharmacies", link: "/drugstore-pharmacies" },
        { label: "Malls & Shopping Centers", link: "/malls-shopping" },
        { label: "Fitness Centers and Gyms", link: "/fitness-gyms" },
        { label: "Office and Commercial Buildings", link: "/office-commercial" },
        { label: "Commercial Cleaning Service", link: "/commercial-cleaning" },
        { label: "Retail", link: "/retail" },
        { label: "Automotive", link: "/automotive" },
      ],
    },
    {
      label: "Service Areas",
      link: "/service-areas",
      sublinks: [
        { label: "Bartlett Cleaning", link: "/bartlett-cleaning" },
        { label: "Gatlinburg Cleaning", link: "/gatlinburg-cleaning" },
        { label: "Chattanooga Cleaning", link: "/chattanooga-cleaning" },
        { label: "Hendersonville Cleaning", link: "/hendersonville-cleaning" },
        { label: "Kingsport Cleaning", link: "/kingsport-cleaning" },
        { label: "Knoxville Cleaning", link: "/knoxville-cleaning" },
        { label: "Memphis Cleaning", link: "/memphis-cleaning" },
        { label: "Nashville Cleaning", link: "/nashville-cleaning" },
      ],
    },
    {
      label: "Services",
      link: "/services",
      sublinks: [
        { label: "Green Cleaning", link: "/green-cleaning" },
        { label: "Waste Removal", link: "/waste-removal" },
        { label: "Disaster Cleaning", link: "/disaster-cleaning" },
        { label: "Construction Cleaning", link: "/construction-cleaning" },
        { label: "Lawn Care", link: "/lawn-care" },
        { label: "Painting", link: "/painting" },
        { label: "Handyman", link: "/handyman" },
        { label: "Post Construction Cleaning", link: "/post-contruction-cleaning" },
        { label: "Move-out, Move-in", link: "/move-in-move-out" },
        { label: "Floor Cleaning ", link: "/floor-cleaning" },
        { label: "Janitorial", link: "/janitorial" },
        { label: "Power Washing", link: "/power-washing" },
        { label: "Window cleaning", link: "/window-cleaning" },
        { label: "Carpet Cleaning", link: "/carpet-cleaning" },
      ],
    },
    { label: "About", link: "/about" },
    {label: "CEJR", link: "/cejr"},
    {label: "Contact Us", link: "/contact-us"},
    {label: "Insurance Coverage", link: "/insurance-coverage"},
    {label: "Privacy Policy", link: "/privacy-policy"},
  ];

// export const footerLinks = [
//   { label: "Residential", link: "/residential" },
//   { label: "Commercials", link: "/commercials" },
//   { label: "Service Areas", link: "/service-areas" },
//   { label: "Services", link: "/services" },
//   { label: "About", link: "/about" },
//   { label: "CEJR", link: "/cejr" },
// ];
